[package]
name = "compositor"
version = "0.1.0"
edition = "2021"

[dependencies]
emulator.path = "../emulator"
pty.path = "../pty"
nix = { version = "0.29", features = ["fs"] }
libc = "0.2"
chrono = "0.4"