[package]
name = "shell"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
libc = "0.2.178"
raw_tty = "0.1.0"
nix = { version = "0.29", features = ["term", "process", "signal", "fs"] }
vte = "0.13"
