[package]
name = "emulator"
version = "0.1.0"
edition = "2021"

[dependencies]
vte = "0.13"

[dev-dependencies]
pty = { path = "../pty" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
